name: Frontend CI/CD
# Using GitHub Action

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install
      working-directory: lovemapped-react

    - name: Run tests
      run: npm test
      working-directory: lovemapped-react

    - name: Build project
      run: npm run build
      working-directory: lovemapped-react



  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v3

  #   - name: Setup Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 22

  #   - name: Install dependencies
  #     run: npm install

  #   - name: Build Docker Image
  #     run: |
  #       docker build -t lovemapped-frontend ./lovemapped-react

  #   - name: Run Docker Locally
  #     run: |
  #       docker run -d -p 3000:3000 lovemapped-frontend
